const words: Record<string, string> = {
  'Activate hand tool': 'Перемещение полотна',
  'Activate lasso tool': 'Выделение области',
  'Activate create/remove space tool': 'Добавить или убрать пространство',
  'Activate global connect tool': 'Соединить элементы',
  'Create start event': 'Добавить стартовое событие',
  'Create intermediate/boundary event': 'Добавить промежуточное событие',
  'Create end event': 'Добавить конечное событие',
  'Create gateway': 'Добавить шлюз',
  'Create task': 'Добавить задачу',
  'Create expanded sub-process': 'Добавить подпроцесс',
  'Create data object reference': 'Добавить объект данных',
  'Create data store reference': 'Добавить хранилище данных',
  'Create pool/participant': 'Добавить пул / участника',
  'Create group': 'Добавить группу',
  'Append end event': 'Добавить конечное событие',
  'Append gateway': 'Добавить шлюз',
  'Append task': 'Добавить задачу',
  'Append intermediate/boundary event': 'Добавить промежуточное событие',
  'Add text annotation': 'Добавить аннотацию',
  'Change element': 'Изменить тип элемента',
  Delete: 'Удалить',
  'Connect to other element': 'Соединить с элементом',
  'Append {type}': 'Добавить {type}',
  'Start Event': 'Стартовое событие',
  'End Event': 'Конечное событие',
  'Intermediate Throw Event': 'Промежуточное отправляющее событие',
  'Intermediate Catch Event': 'Промежуточное принимающее событие',
  Task: 'Задача',
  'User Task': 'Пользовательская задача',
  'Service Task': 'Сервисная задача',
  'Script Task': 'Скриптовая задача',
  'Manual Task': 'Ручная задача',
  'Business Rule Task': 'Задача бизнес-правил',
  'Send Task': 'Задача отправки',
  'Receive Task': 'Задача получения',
  'Exclusive Gateway': 'Исключающий шлюз',
  'Parallel Gateway': 'Параллельный шлюз',
  'Inclusive Gateway': 'Включающий шлюз',
  'Complex Gateway': 'Комплексный шлюз',
  'Event based Gateway': 'Событийный шлюз',
  'Event-based Gateway': 'Событийный шлюз',
  'Sub Process': 'Подпроцесс',
  'Sub-process': 'Подпроцесс',
  'Expanded Sub Process': 'Развёрнутый подпроцесс',
  'Collapsed Sub Process': 'Свёрнутый подпроцесс',
  'Call Activity': 'Вызов процесса',
  Transaction: 'Транзакция',
  Search: 'Поиск',
  'Search ...': 'Поиск…',
  'No results found': 'Ничего не найдено',
  'No matches found.': 'Ничего не найдено',
  'Change type': 'Изменить тип',
  'Change element type': 'Изменить тип элемента',
  Remove: 'Удалить',
  'Add lane above': 'Дорожка сверху',
  'Add lane below': 'Дорожка снизу',
  'Divide into two lanes': 'Разделить на две дорожки',
  'Divide into three lanes': 'Разделить на три дорожки',
  'Add Lane': 'Добавить дорожку',
  Participant: 'Участник',
  Lane: 'Дорожка',
  'Text Annotation': 'Текстовая аннотация',
  Group: 'Группа',
  'Data Object Reference': 'Объект данных',
  'Data Store Reference': 'Хранилище данных',
  'Sequence Flow': 'Поток управления',
  'Message Flow': 'Поток сообщений',
  Association: 'Ассоциация',
  'Default Flow': 'Ветка по умолчанию',
  'Conditional Flow': 'Условная ветка',
  Loop: 'Цикл',
  'Parallel Multi Instance': 'Параллельное выполнение',
  'Sequential Multi Instance': 'Последовательное выполнение',
  'Ad-hoc': 'Нерегламентированный',
  Compensation: 'Компенсация',
};
function translate(template: string, replacements: Record<string, string> = {}) {
  let result = words[template] || template;
  for (const [key, value] of Object.entries(replacements))
    result = result.replaceAll('{' + key + '}', words[value] || value);
  return result;
}
export default { translate: ['value', translate] };
